/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as RegisterReviewRouteImport } from './routes/register.review'
import { Route as RegisterFormRouteImport } from './routes/register.form'
import { Route as RegisterAlreadyRouteImport } from './routes/register.already'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGraduatedRouteImport } from './routes/admin.graduated'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students.$id'
import { Route as AdminStudentsIdEditRouteImport } from './routes/admin.students.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterReviewRoute = RegisterReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterFormRoute = RegisterFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterAlreadyRoute = RegisterAlreadyRouteImport.update({
  id: '/already',
  path: '/already',
  getParentRoute: () => RegisterRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGraduatedRoute = AdminGraduatedRouteImport.update({
  id: '/graduated',
  path: '/graduated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdEditRoute = AdminStudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminStudentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/graduated': typeof AdminGraduatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/register/already': typeof RegisterAlreadyRoute
  '/register/form': typeof RegisterFormRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/graduated': typeof AdminGraduatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/register/already': typeof RegisterAlreadyRoute
  '/register/form': typeof RegisterFormRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/graduated': typeof AdminGraduatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/register/already': typeof RegisterAlreadyRoute
  '/register/form': typeof RegisterFormRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/register'
    | '/admin/duplicates'
    | '/admin/exports'
    | '/admin/graduated'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/registrations'
    | '/admin/settings'
    | '/register/already'
    | '/register/form'
    | '/register/review'
    | '/register/success'
    | '/admin/'
    | '/register/'
    | '/admin/students/$id'
    | '/admin/students/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/admin/duplicates'
    | '/admin/exports'
    | '/admin/graduated'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/registrations'
    | '/admin/settings'
    | '/register/already'
    | '/register/form'
    | '/register/review'
    | '/register/success'
    | '/admin'
    | '/register'
    | '/admin/students/$id'
    | '/admin/students/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/register'
    | '/admin/duplicates'
    | '/admin/exports'
    | '/admin/graduated'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/registrations'
    | '/admin/settings'
    | '/register/already'
    | '/register/form'
    | '/register/review'
    | '/register/success'
    | '/admin/'
    | '/register/'
    | '/admin/students/$id'
    | '/admin/students/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/review': {
      id: '/register/review'
      path: '/review'
      fullPath: '/register/review'
      preLoaderRoute: typeof RegisterReviewRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/form': {
      id: '/register/form'
      path: '/form'
      fullPath: '/register/form'
      preLoaderRoute: typeof RegisterFormRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/already': {
      id: '/register/already'
      path: '/already'
      fullPath: '/register/already'
      preLoaderRoute: typeof RegisterAlreadyRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/graduated': {
      id: '/admin/graduated'
      path: '/graduated'
      fullPath: '/admin/graduated'
      preLoaderRoute: typeof AdminGraduatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$id/edit': {
      id: '/admin/students/$id/edit'
      path: '/edit'
      fullPath: '/admin/students/$id/edit'
      preLoaderRoute: typeof AdminStudentsIdEditRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
  }
}

interface AdminStudentsIdRouteChildren {
  AdminStudentsIdEditRoute: typeof AdminStudentsIdEditRoute
}

const AdminStudentsIdRouteChildren: AdminStudentsIdRouteChildren = {
  AdminStudentsIdEditRoute: AdminStudentsIdEditRoute,
}

const AdminStudentsIdRouteWithChildren = AdminStudentsIdRoute._addFileChildren(
  AdminStudentsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminGraduatedRoute: typeof AdminGraduatedRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminGraduatedRoute: AdminGraduatedRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RegisterRouteChildren {
  RegisterAlreadyRoute: typeof RegisterAlreadyRoute
  RegisterFormRoute: typeof RegisterFormRoute
  RegisterReviewRoute: typeof RegisterReviewRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterAlreadyRoute: RegisterAlreadyRoute,
  RegisterFormRoute: RegisterFormRoute,
  RegisterReviewRoute: RegisterReviewRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
